os: Visual Studio 2017

environment:
    image: Visual Studio 2017
    Configuration: Release

build_script:
  - cmd: msbuild /t:restore;build /v:m /m .\KeePass.sln

after_build:
  - cmd: msbuild /t:pack .\KeePassLib\KeePassLib.csproj

test_script:
  - cmd: dotnet test .\KeePassLibTest\KeePassLibTest.csproj

artifacts:
  - path: '**\bin\**\*.nupkg'